### ISSUE TITLE
Tracking issue: Migrate pages from old version

### ISSUE THREAD

**Issue by Trayshar** [dapnet-core/frontend#5]
- [ ] New call
- [ ] New/Edit subscriber
- [ ] All transmitters
- [ ] New/Edit transmitter
- [ ] All rubrics
- [ ] New/Edit rubric
- [ ] Edit rubric content
- [ ] All users
- [ ] New/Edit user
- [ ] All nodes
- [ ] New/Edit node
- [ ] Map
- [ ] Impress
- [ ] Privacy

The `My xyz` pages should probably be a variation of the normal page with an additional filter (that has to be supported by the pagination logic). Maybe don't port them at all and have a multiple-choice filter for 'owner' instead

- [ ] My transmitters
- [ ] My rubrics
- [ ] My subsrcibers
- [ ] My nodes
