### ISSUE TITLE
Tracking Issue: Map

### ISSUE THREAD

**Issue by Trayshar** [dapnet-core/frontend#7]
Map is not finshed yet. Most of this is documented with `TODO:` comments in `MapComponent.vue`

- [ ] Cluster transmitters if zoomed out
- [ ] Center map on transmitter selection
- [ ] Try different styles for info card in top left
- [ ] Coverage map

It's also worth noting that the map library choice, [Vue3-OpenLayers](https://github.com/MelihAltintas/vue3-openlayers), might not have been ideal:
- Large bundle size. Seems like tree-shaking doesn't work. *TODO: Investigate and open ticket upstream*
- *EPSG:4326* projection looks distorted, so *EPSG:3857* is used internally. No limitation, just adds complexity (coordinate transformation). *TODO: Make minimal working example and re-open ticket upstream*
- Some other open, still unresolved issues that I had to work around (it works - but maintainability is subpar)
